"""empty message

Revision ID: 3015755e37e8
Revises: c49302efcded
Create Date: 2016-09-28 17:32:28.443248

"""

# revision identifiers, used by Alembic.
revision = '3015755e37e8'
down_revision = 'c49302efcded'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    ### end Alembic commands ###
